### ISSUE TITLE
Compile source code

### ISSUE THREAD

**Issue by NestorAlbelo** [robhagemans/pcbasic#1]
Hi, 
I am trying to compile the source code but I do not know exactly how to do that. I have tried to execute "/packaging/source/build.sh" script but it fails. I am using Ubuntu 15.04 and I have already install all the dependencies, that  are needed.

Thanks =D

**Comment by robhagemans** [comment]
There is no need to compile, just run the pcbasic file (it's executable python file)

**Comment by NestorAlbelo** [comment]
Sorry i mean to package it

**Comment by robhagemans** [comment]
Why would you need to package it?

**Comment by robhagemans** [comment]
It's easiest to just run the program directly from the source directory, the packaging is just intended for easy distribution. 

However, if you really do want to package you would need to run packaging/prepare.sh and then packaging/source/build.sh .

**Comment by robhagemans** [comment]
Sorry, just noted the stack trace about ansipipe, which somehow only shows on github, not in the mail I got. Looks like you're missing the ansipipe directory, which is a git submodule.

Ansipipe is a workaround for Windows and really does nothing on Linux, so you could alternatively comment out all lines referring to ansipipe.

Rob

**Comment by NestorAlbelo** [comment]
Hi!!
I really appreciate your answers I will try it now, and I will let you know what I get
Thanks =D

**Comment by robhagemans** [comment]
If you got the source through git clone, you need to run these two commands to get ansipipe:

git submodule init
git submodule update

Hope this solves your problem, let me know how it goes.

Rob

**Comment by NestorAlbelo** [comment]
Hey I have just tried adding the submodule and it works fine, thank you for answering so fast 

Nestor

**Comment by robhagemans** [comment]
You're welcome, have fun using PC-BASIC!
