### ISSUE TITLE
Issue access LPT1 (F6)

### ISSUE THREAD

**Issue by bdecamps** [robhagemans/pcbasic#100]
## Bug report

**Problem**

**Steps**

1.  
2.  
3.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by bdecamps** [comment]
problem: i used old program working with gwbasic with pc-basic. I got trouble with F6 (LPT1) getting syntax error when i press on f6 plus enter. The program i used worked perfectly and i got the results printed on my brother when I closed pc-basic. I wanted to modify the output lpt1 on a file but i can't access the lpt1. Can you help me? Thanks in advance.

**Comment by bdecamps** [comment]
My version of pc-basic is 1.2.14

**Comment by bdecamps** [comment]
my operating system is mac High sierra 10.13.6

**Comment by robhagemans** [comment]
Hi, thanks for getting in touch!

F6 plus enter is expected to give you a Syntax Error, as `,"LPT1"` is not a valid BASIC statement. F6 is not intended to be a command. To send output somewhere else than to the printer, you need to change the settings in the configuration file at `~/Library/Application Support/pcbasic-1.2/PCBASIC.INI`
See http://robhagemans.github.io/pcbasic/doc/1.2/#settings for more information.

**Comment by robhagemans** [comment]
I'll close this issue - please feel free to reopen if you're running into any further issues.
