### ISSUE TITLE
Distributing pcbasic on filegate

### ISSUE THREAD

**Issue by andy5995** [robhagemans/pcbasic#103]
Hi @robhagemans ,

Would you be interested in having pcbasic distributed on [FileGate](http://www.filegate.net/)?

**Comment by andy5995** [comment]
Oh! I see it already is! http://www.filegate.net/pdnbasic/

**Comment by robhagemans** [comment]
Hi Andy, actually I see little advantage in having releases distributed on different sites - people can do this if they want of course but inescapably they will end up having out of date releases. The latest official release is always here on Github (and linked through pc-basic.org).
