### ISSUE TITLE
Documentation lacks section "Memory model", causing a broken link in POKE statement doc

### ISSUE THREAD

**Issue by nmanumr** [robhagemans/pcbasic#11]
Inside POKE statement there is an broken link in side note heading "Memory model". http://robhagemans.github.io/pcbasic/doc/#memory

**Comment by robhagemans** [comment]
Thanks - that section of the documentation has not yet been written but will be added once it has.

Rob

**Comment by robhagemans** [comment]
Fixed by commits e48afd1 (16.12) and 66e4286 (15.08)
