### ISSUE TITLE
--logfile not writting date

### ISSUE THREAD

**Issue by Danitegue** [robhagemans/pcbasic#110]
The current pcbasic is only writting in the logfiles hour:minute:second.milisecond
Is possible to add also day/month/year?
This would help to research when a problem started happening. 
Best regards

**Comment by robhagemans** [comment]
Hi @Danitegue , unfortunately I don't have a lot of time to dedicate to PC-BASIC at the moment. However you can easily change the logging format to your needs by changing the `LOGGING_FORMAT` constant in `config.py`.

**Comment by Danitegue** [comment]
Ok, that would be enough. Thanks
