### ISSUE TITLE
pcbasic crashes when returning from "Description of program" in COMM.BAS 

### ISSUE THREAD

**Issue by Himel55** [robhagemans/pcbasic#112]
## Bug report
**Problem**
I downloaded DOS 1.1 Samples from here http://peyre.x10.mx/GWBASIC/ 
When trying out the COMM.BAS program and returning from the "Description of program" menu item by pressing any key, pcbasic crashes.

**Steps**
1.  Download samples from link mentioned above
2.   LOAD"COMM.BAS"
3.  RUN
4. press 1 (to select description choice)
5. press any key to return (I pressed enter)

**Crash log**
```
EXCEPTION                                                                       
30 WIDTH "com1:",255:DEF SEG                                                                                                                                    
run.py:66, run_once                                                             
    None                                                                        
statements.py:132, parse_statement                                              
    None                                                                        
statements.py:2480, exec_width                                                  
    None                                                                        
AttributeError: 'NoneType' object has no attribute 'set_width'
```
**Notes**

PC-BASIC version:  1.2.14
Operating system version:  Windows 10 Build 17763

**Comment by robhagemans** [comment]
This is the same issue as https://github.com/robhagemans/pcbasic/issues/98, fixed in repo.
