### ISSUE TITLE
Shift+Insert to Paste?

### ISSUE THREAD

**Issue by mgregory22** [robhagemans/pcbasic#117]
Could you extend it a little and implement Shift-Insert to paste text into the window?  According to my DOSBOX version, GWBASIC treats Shift+Insert the same as Insert, so I don't think it would hurt compatibility or anything.

**Comment by robhagemans** [comment]
Sorry, but if GW-BASIC treats shift-insert the same as insert then so should PC-BASIC - programs may rely on these working the same. This is why the clipboard operations were implemented with F11 as GW-BASIC does not recognise this key.
