### ISSUE TITLE
"CHAIN" command

### ISSUE THREAD

**Issue by BASICLFE** [robhagemans/pcbasic#118]
## Bug report

**Problem**

I have individual programs that use the CHAIN command to advance from one program to the other. It was successful in "chaining" two programs; but on the third it came back with:

pc.basic.var: 159, clear_variables
    None
pc.basic.var: 81, get_string_copy_packed
    None
pc.basic.var: 49, copy_packed
     None
pc.basic.var: 40, retrieve
      None
KeyError;  '\xfd\xfd'

Can you tell me what is the issue?

**Steps**

1.  
2.  
3.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by robhagemans** [comment]
Can you post the programs and the PC-BASIC version? From the information
given I won't be able to reproduce the issue.

**Comment by robhagemans** [comment]
Closing as insufficient information provided. Please re-open if you have the details needed.
