### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by squirrelhavoc** [robhagemans/pcbasic#12]
As I was entering simple programs to test new things, specifically printing with lprint, I came across this error:

EXCEPTION
version   16.12.0rc0
platform  Windows-10-10.0.14393-SP0
statement 30 LPRINT "X is ", X

statements.py:90, parse_statement
files.py:649, lprint_
formatter.py:32, format
formatter.py:65, _print_comma
TypeError: write() got an unexpected keyword argument 'can_break'
This is a bug in PC-BASIC.Sorry about that. 

I am wondering if it is even allowed to use a comma in lprint output formatting, but I am new and still learning how everything works, so I was trying new things with formatting and printing.

[pcbasic-crash-20161208-1a4hjk.zip](https://github.com/robhagemans/pcbasic/files/641212/pcbasic-crash-20161208-1a4hjk.zip)

In case it matters, I have printing redirected to a file "output.txt" as I don't even have a printer right now.

**Comment by robhagemans** [comment]
Thanks for reporting and for attaching the log! I'll fix this bug.

The syntax for LPRINT is identical to that for PRINT, with the exception
that you can't give a file argument (ie you can't do LPRINT#1) - so in
principle the comma should be no problem.

**Comment by robhagemans** [comment]
Fixed, will be in next prerelease.
