### ISSUE TITLE
PC-Basic Bug

### ISSUE THREAD

**Issue by Bill007007** [robhagemans/pcbasic#14]
I wrote a little program to approximate Pi.   I received an error message about a bug in PC-Basic.

100 K=-1
102 PI#=0#
105 K=K+1
106 IF K=101 THEN GOTO 150
110 L=2*K+1
115 PI#=PI#+4#*((-1)^K/L*(1#/(2#^L)+1#/(3#^L))
130 PRINT "K= ";K;"PI= ";PI#
140 GOTO 105
150 END

William

**Comment by robhagemans** [comment]
Hi William, thanks for reporting! I'll investigate the issue.

**Comment by robhagemans** [comment]
100 K=-1
    102 PI#=0#
    105 K=K+1
    106 IF K=101 THEN GOTO 150
    110 L=2*K+1
    115 PI#=PI#+4#*(-1)^K/L*(1#/(2#^L)+1#/(3#^L))
    130 PRINT "K= ";K;"PI= ";PI#
    140 GOTO 105
    150 END

    expressions.py:869, value_operator
        return vcaret(left, right)
    expressions.py:924, vcaret
        return fp.pack( fp.power(fp.unpack(vartypes.pass_single_keep(left)), fp.unpack(vartypes.pass_single_keep(right))) )
    fp.py:479, pack
        s = n.to_bytes()
    fp.py:131, to_bytes
        s.append(self.exp)
    ValueError: byte must be in range(0, 256)

**Comment by robhagemans** [comment]
Fixed related issue in 16.12 branch, bug remains open in 15.08 branch

**Comment by robhagemans** [comment]
Fixed by commit 735e63e (15.08) and commit e464996 (16.12)
