### ISSUE TITLE
Window has white border until you grab and move the window

### ISSUE THREAD

**Issue by JDoucette** [robhagemans/pcbasic#157]
## Bug report

**Problem**
White border is inconsistent.
It shows, then disappears when you move the window.

What I expect is that there is never any white border to begin with, since it makes the window sort of ugly.  When I capture a video using Windows+G video screen capture, you can see the ugly white border: https://www.youtube.com/watch?v=zV9gyMotXXw  Now I know to move the window first, so that it disappears. :) 

**Steps**
Start PC-BASIC in Windows 10.
Grab the title bar and move the window.
The white border disappears.

**Program**
No program needed.

**Crash log**
No crash.

**Notes**
PC-BASIC 1.2.14                         
Operating system version:  Windows 10

Please consider removing the white border entirely. :)
(And thanks SO MUCH for making this emulator!)

**Comment by rbergen** [comment]
I can't reproduce this with version 2.0.4. @JDoucette Maybe you can check if the issue still occurs in that version on your system?

**Comment by JDoucette** [comment]
I confirmed this does not happen in 2.0.4.
