### ISSUE TITLE
OPTION BASE should be allowed after ERASEing all arrays

### ISSUE THREAD

**Issue by robhagemans** [robhagemans/pcbasic#185]
Test code:

    DIM Y%(4)
    OPTION BASE 1
    ERASE Y%
    OPTION BASE 1    

What happens:

    Duplicate Definition
    Ok
    Duplicate Definition
    Ok

What should happen:

    Duplicate Definition
    Ok
    Ok

Background - `OPTION BASE` should fail with `Duplicate Definition` if there are allocated arrays. However, if all arrays have been `ERASE`d it should be allowed. PC-BASIC disallows it if at any point an array has been allocated

**Comment by rbergen** [comment]
Wow, I'd put this in the "rather obscure" category, for sure. I can't help wondering how on earth you found this one. :)

**Comment by robhagemans** [comment]
As almost always, by accident... Though in the context of issue #182 it's not quite so random.

**Comment by rbergen** [comment]
I had missed #182. But yes, I do see the connection now.

**Comment by robhagemans** [comment]
Fixed by commit e2611007

**Comment by robhagemans** [comment]
As almost always, by accident... Though in the context of issue #182 it's
not quite so random.
