### ISSUE TITLE
 MacOS Universal Code release for M1 Apple Silicon

### ISSUE THREAD

**Issue by Alessandro1970** [robhagemans/pcbasic#189]
I wonder if it is possible to download a version for MacOs compatible not only X86-64 but also fot CPU-Arm (M1 / Apple Silicon)

**Comment by robhagemans** [comment]
Hi, that depends if someone is willing to release and maintain a package
for that platform.

At the moment all Mac releases have been discontinued due to Apple's
requirements for code signing which I'm unable to satisfy.

Thanks,
Rob

**Comment by incanus** [comment]
Some work related to this going on over in https://github.com/robhagemans/pcbasic/issues/131#issuecomment-1193035013; we can probably close here @robhagemans.

**Comment by robhagemans** [comment]
Merging into #131 per @incanus's suggestion
