### ISSUE TITLE
SAVE" BUG

### ISSUE THREAD

**Issue by sadams16m** [robhagemans/pcbasic#220]
## Bug report

**Problem**

IF I do a SAVE"DIOPTR12.BAS", A  ; IT WORKS NORMAL ,
BUT if the last quote " at the end of .BAS"  like ( SAVE"DIOPTR12.BAS , A  ) is left off, THEN CHINESE LANGUAGE IS SAVED TO FILE DIOPTR12.BAS , INSTEAD OF A ENGLISH LANGUAGE BASIC PROGROM IN ASCII ]

**Steps**

1.   SAVE"DIOPTR12.BAS , A  
2.  
3.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  2.0.6
Operating system version:  WINDOWS 11 HOME V.22H2, 64 BIT, OS BUILD: 22621.963

**Comment by robhagemans** [comment]
Hi, this is not a bug, and it's not Chinese but the tokenised file format. See here in the documentation https://robhagemans.github.io/pcbasic/doc/2.0/#SAVE
