### ISSUE TITLE
PC-BASIC2.0.6 wont start - VCRUNTIME140.dll not found

### ISSUE THREAD

**Issue by keithnigelwilliams** [robhagemans/pcbasic#221]
## Bug report

**Problem**

**Steps**

1.  
2.  
3.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by keithnigelwilliams** [comment]
I've had to re-install PC-BASIC 2.0.6 onto a RESETed Windows 11 PC but it won't start, saying VCRUNTIME140.dll is not found.
It seems to install correctly.

**Comment by keithnigelwilliams** [comment]
2.0.6 still won't start but I'm using 1.2.15 as a workaround. 
knw@msn.com

**Comment by robhagemans** [comment]
Hi, not sure why this happens on your Windows 11 or whether I can reproduce the issue. Normally the required VC dlls get installed correctly.

The missing file is the standard Microsoft Visual C++ 2015 runtime. You can try to install the dll separately by downloading *Microsoft Visual C++ 2015 Redistributable* directly from Microsoft - see https://www.microsoft.com/en-us/download/details.aspx?id=52685 and the installation instructions on that page.

**Comment by keithnigelwilliams** [comment]
Very many thanks, C++ downloaded via your link and all is now well. No idea why it happened, everything else is/was fine.
Thanks again, Keith Williams

**Comment by keithnigelwilliams** [comment]
Very many thanks, C++ downloaded via your link and all is now well. No idea why it happened, everything else is/was fine.
Thanks again, Keith Williams
