### ISSUE TITLE
Bug in PCBASIC 2.0.7 for Linux won't open due by DBUS error

### ISSUE THREAD

**Issue by cesarmarcanove** [robhagemans/pcbasic#228]
Bug encountered in PCBASIC v2.0.7 for Linux

PC BASIC doesn't open the app and appears says:

>
> dbus[4005]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
> This is normally a bug in some application using the D-Bus library.
> 
>   D-Bus not built with -rdynamic so unable to print a backtrace
> Abortado (`core' generado)
>
> 

See image the bug
![bug-pcbasic207](https://github.com/robhagemans/pcbasic/assets/279859/c25ea320-9e25-4d34-ae47-213c18914239)

**Notes**

PC-BASIC version:  2.0.7
Operating system version:  Ubuntu / Debian 9+

**Comment by robhagemans** [comment]
How did you install pc-basic/which package did you use?

Not sure what days is or how it is being used. It may be related to the SDL
interface. Is it possible to start in text mode? E.g. through pcbasic -b or
pcbasic -n

Which distribution and version do you use? I.e. is it Debian or Ubuntu, as
you mention both, and I don't recognise the version number 9+

**Comment by cesarmarcanove** [comment]
Ubuntu 18.04 32 bits

**Comment by robhagemans** [comment]
And how did you install? Could be through pip, through apt/Ubuntu software
centre or through the .deb published on the pc basic web site.

Also please let me know if text mode works

**Comment by cesarmarcanove** [comment]
I retried the reinstallation with the DEB and the app does not exit, and it exits silently due to the same error as in the command terminal (CLI).

The app does not respond, and perhaps with the argument "-b" with version warning and "-n" without version warning.

**Comment by robhagemans** [comment]
This seems to be an issue with SDL2 on 32-bit Ubuntu, see e.g. here. https://stackoverflow.com/questions/52702683/sdl-initsdl-init-video-generating-excpetion-dbus3856-about-dbus-library

This is not something I can resolve or work around in PC-BASIC, your best bet will be to file a bug report with Ubuntu on their SDL2 package.
