### ISSUE TITLE
Greek codepages, didn't work for me.

### ISSUE THREAD

**Issue by Achaean** [robhagemans/pcbasic#233]
## Bug report

**Problem**

Codepages 737 and 851, doesn't seems to work for me.

**Steps**

I tried to run a Hello world program.
```
>cat HELLO.BAS
10 PRINT "Γειά σου κόσμε"
>
```

I'm attaching a screenshot.

**Notes**

PC-BASIC version:  Latest (2.0.7).
Operating system version:  On a Debian based system x64.
![Screenshot](https://github.com/robhagemans/pcbasic/assets/3608053/df9e44e2-cf1a-4e9a-8cf7-927d684ddb60)

**Comment by robhagemans** [comment]
Hi, `codepage=737` is not a BASIC command but a configuration setting.

Please see http://robhagemans.github.io/pcbasic/doc/2.0/#changing-settings on how to change configuration settings.

**Comment by Achaean** [comment]
Ooops!!! Mea culpa!  :-)
Seems like I failed to locate this specific part of documentation.

THANKS Rob and have a Happy New Year!!!  ;-)
