### ISSUE TITLE
chdir ".." nothing changes.

### ISSUE THREAD

**Issue by nganfei** [robhagemans/pcbasic#234]
## Bug report

**Problem**

chdir ".." nothing changes. in version 2.0.7
**Steps**

1.    files
2.    type in chdir ".." 
3.    type in files again
4.    "both files" shows the same directory.

**Program**

**Crash log**

**Notes**

PC-BASIC version:  2.0.7
Operating system version:  Linux

**Comment by robhagemans** [comment]
There's no output to check, but you're probably at the root directory of
the PC-BASIC drive (e.g. Z:\) so there is no directory above.
