### ISSUE TITLE
Apple support tell me I can't run PC-BASIC 2.0.6 or .7 on a 2024 IPad Pro , IOS 17. Is this still true.

### ISSUE THREAD

**Issue by keithnigelwilliams** [robhagemans/pcbasic#245]
## Bug report

**Problem**

**Steps**

1.  
2.  
3.  

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by robhagemans** [comment]
I don't have an iOS release for PC-BASIC so I expect that's true. You might be able to install Python on iOS and get it working but it's not something I have time to support

**Comment by keithnigelwilliams** [comment]
Very many thanks for replying. I'll just have to be patient and keep the
Windows machine going!
