### ISSUE TITLE
Accented French characters in PC-Basic

### ISSUE THREAD

**Issue by Ycarca** [robhagemans/pcbasic#41]
Trying to use codepage 850 or 863,  the French accented characters are shown on the screen preceded by an apostrophe or a bracket  ( Seems default codepage 437 does the same )
à  appears as   `à
ô also shown as [ô

è  gives     `è

and â  appears as    [â
The characters are produced by a combination of two keys and  the printed result is the  first key itself followed by the character

also, I cannot get uppercase accented characters for those letters.

I use Win 7 Pro

Thank you for your attention.
Claude

**Comment by robhagemans** [comment]
See https://sourceforge.net/p/pcbasic/discussion/bugs/thread/dd9ebe52/
