### ISSUE TITLE
Commenting out ansipipe leads to an error.

### ISSUE THREAD

**Issue by mobluse** [robhagemans/pcbasic#43]
Hi,
I tested this in Ubuntu in WSL (AKA BashOnWindows) on Windows 10 and it worked well! Now I wanted to test it on my web hotel https://www.one.com/ via `ssh`, but then `git clone --recursive` didn't work completely, see error below. The problems are with ansipipe. Since this web hotel doesn't have gcc I doubt that ansipipe could work even if I could download it because it seems to be a C program in source form. I saw you mentioned in #1 that ansipipe was not necessary and could be commented out. I did this in the file ./pcbasic/main.py , but that led to an error. I could type `system` to quit BASIC.
```
  EXCEPTION
  version   16.12.0rc0
  platform  Linux-4.4.39-20170104-1142-143834a-x86_64-with-glibc2.7
  statement

  values.py:89, wrapped_fn
  values.py:262, from_repr
  numbers.py:264, from_str
  numbers.py:171, from_int
  TypeError: expected a writeable buffer object

  This is a bug in PC-BASIC.
  Sorry about that. Please file a bug report at
    https://github.com/robhagemans/pcbasic/issues
  Please include the messages above and as much information as you can about wha  you were doing and how this happened. If possible, please attach the log file
    /home/orbin.se/.local/share/pcbasic-dev/pcbasic-crash-20170925-Q1jBwI.log
  This file contains detailed information about your program and this crash.
  Thank you!
  Ok?

```

```
$ git clone --recursive https://github.com/robhagemans/pcbasic
Cloning into 'pcbasic'...
remote: Counting objects: 32393, done.
remote: Total 32393 (delta 0), reused 0 (delta 0), pack-reused 32393
Receiving objects: 100% (32393/32393), 12.08 MiB | 6.00 MiB/s, done.
Resolving deltas: 100% (22432/22432), done.
Checking out files: 100% (2386/2386), done.
Submodule 'ansipipe' (git://github.com/robhagemans/ansipipe.git) registered for path 'pcbasic/ansipipe'
Cloning into 'pcbasic/ansipipe'...
fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out

Clone of 'git://github.com/robhagemans/ansipipe.git' into submodule path 'pcbasic/ansipipe' failed
```
```
$ arch
x86_64
```

**Comment by robhagemans** [comment]
It's probably best to try and get the full clone to work - from the log it looks like there was a github connection problem and quite probably more than just ansipipe could be missing.
You won't need the C source or a compiler or Linux, but it does import a python module that's in the ansipipe directory.

I'm not sure where the error you see comes from, but it doesn't look ansipipe-related. On my own Ubuntu machine, I don't see this error when I comment out ansipipe.

If the clone doesn't work, you can install on Ubuntu from one of the .tgz releases, either the stable version 15.08.1
https://github.com/robhagemans/pcbasic/releases/download/15.08.11/pcbasic-15.08.11.tgz

or the development version 16.12.0rc0
https://github.com/robhagemans/pcbasic/releases/download/16.12.0rc0/pcbasic-16.12.0rc0.tgz

If it still crashes with the full install, could you attach the crash log?

**Comment by mobluse** [comment]
I tried https://github.com/robhagemans/pcbasic/releases/download/16.12.0rc0/pcbasic-16.12.0rc0.tgz , but I get the same error. When I install to pcbasic it says:
```
Checking dependencies ...
checking Python module xdg ... installed
checking Python module pygame ... NOT INSTALLED
checking Python module numpy ... NOT INSTALLED
checking Python module serial ... NOT INSTALLED
checking Python module parallel ... NOT INSTALLED
checking Python module pexpect ... installed

WARNING: The following Python modules were not found:  pygame numpy serial parallel
Please install them separately to ensure all PC-BASIC functionality works correctly.

INSTALLATION COMPLETED. 
```

I have successfully installed xdg, serial, and parallel, but it still says serial and parallel is uninstalled. I installed e.g. using
`python -m pip -v install parallel --user`
I had to use `--user` otherwise it would not install. I don't have `sudo` on this account.

I could not install numpy because the process was killed for some unknown reason.
[pcbasic-crash-20171014-Fk10TX.log](https://github.com/robhagemans/pcbasic/files/1384583/pcbasic-crash-20171014-Fk10TX.log)

**Comment by mobluse** [comment]
The reason why clone of git://github.com/robhagemans/ansipipe.git doesn't work might be that some port is blocked. If it used https instead of git it would probably work.

**Comment by robhagemans** [comment]
I just realised this is the same error as https://github.com/robhagemans/pcbasic/issues/45, which is linked to https://github.com/robhagemans/pcbasic/issues/24. In short: for the dev version, you need Python 2.7.12 or higher, and older Ubuntu doesn't have this.  The stable version should work, though.

Since this issue is covered by https://github.com/robhagemans/pcbasic/issues/24 I'm going to close it, but feel free to re-open if you see further issues.

NB - You can run without `serial` and `parallel` but `numpy` is required for the dev version. The stable version can run without it, though some functionality will be disabled. Without `pygame` you only have a text interface (on the command line). 

I think `pip` installs to a separate location from the regular Ubuntu packages which is why they may not be seen by PC-BASIC. So you'd have to get your administrator to install `numpy` at least, I think, or work from a correctly cloned git. 

If your firewall causes problems, the submodule address is set in `.git/config` so you can change it there and update the submodule - see the git documentation for more on that.
