### ISSUE TITLE
PCBASIC OSX main window

### ISSUE THREAD

**Issue by Alessandro1970** [robhagemans/pcbasic#58]
Hi,
First of all, thank you very much for this excellent basic interpreter, I'll tell about this to all friend of mine.
Secondly I wanted to ask to you if it is possible to create, for the Mac OSX version, a window as seen in my picture with the possibility to customize the options bar (see the reset button and more).
On the one hand it would be more beautiful aesthetically and more in line with applications for mac (see Virtual C64 emulator interface on github [https://github.com/dirkwhoffmann/virtualc64])
![pcbasicformac](https://user-images.githubusercontent.com/34916641/35144366-9e7b87fa-fd04-11e7-84f0-a7a97996e51d.jpg)

**Comment by robhagemans** [comment]
Hi Alessandro, great that you like the interpreter!

At the moment I have no plans to add menus or toolbars to the application, whether for Mac or other OSes.

Rob
