### ISSUE TITLE
Failed to initialise sound.

### ISSUE THREAD

**Issue by naumanumer** [robhagemans/pcbasic#6]
Release: 15.8.10
Plateform: win 10 (64bit)

I am getting following warning constantly 
`WARNING: Failed to initialise sound. Sound will be disabled.`

When running pcbasic with this conmmand
`pcbasic -bqe="beep" --nosound=false`

and also no beep is produced

**Comment by robhagemans** [comment]
Version 15.08.* on Windows has no support for sound on the command line, as PyGame is required for sound.  

Note that this has been addressed in the current development version, however there has not yet been an executable release including this.
