### ISSUE TITLE
Mixing BASIC and Python code

### ISSUE THREAD

**Issue by robhagemans** [robhagemans/pcbasic#60]
[Danitegue:] 
Hi Rob, I have been researching a way to communicate the brewer software with python scripts...

I saw very interesting notes in your devguide, but I have one question more.

When we start the brewer software with pcbasic, a pcbasic session is created. 

How we can intercept this already existing session from a different python script?

Has it a handler or something that we can use for interactuate with the correct session object?

I mean to work in this 2 ways:

a)
-Run the brewer software on pcbasic
-Execute a customized routine in the brewer software (like we did with "pdhphg", but for example "py")
-In the routine file py.rtn will be the python code to be executed, for example:

' it is needed to add a keyword to make understand pcbasic to read the following code as python code, not basic code
s=get_CurrentSessionHandler
a=s.get_variable('HF%')
if a==0:
\t s.set_variable('HF%', 1)

b) 
-Run the brewer software on pcbasic
-From a different python script, get the brewer software variables every 5 minutes to draw a plot with the retrieved values of the vars

**Comment by robhagemans** [comment]
Hi, in first instance I'd say if you want to run Python from the BASIC program, you should use extensions rather than the Session API. That'll allow you to define a function or statement that you can call with the values you need, rather than trying to read them from the session. You can return only a single value from a function, but you could conceivably work around that by using a class with getter-functions, or maybe simply module-level globals. Something like this:

```
values = [0]*10

def calc(a):
    global values
    values = [a**n for n in range(10)]

def getr(n):
    try:
        return values[n]
    except IndexError:
        return -1
```

which would go into a python module (e.g. `myextension.py`) that can then be enabled with the PC-BASIC option `--extension=myextension`. Then, in your BASIC code, you can call these Python functions:

```
_CALC(2) 
PRINT _GETR(4)
 16
Ok 

```
In this way you could write a BASIC wrapper `PYTHON.RTN` that then calls functions from the extension module (which could load them from modules provided by your users) and uses return values to set variables where needed.

If you want to access the session directly from Python code called from BASIC, you'd have to inherit from the `Session` class and call your BASIC code from this extended class: e.g.

```
class ExtendedSession(Session):

    def __init__(self):
        Session.__init__(self, stdio=True, extension=self)

    def adda(self, x):
        print "adda", repr(x), repr(self.get_variable("a"))
        return x + self.get_variable("a")


with ExtendedSession() as s:
    s.execute('''
        a = 4
        b = _adda(1)
        print a, b
    ''')

```
This is of curse all experimental so I can't guarantee that it'll keep working like this in future versions.

To manipulate this session from separately running code as in (b), you could try the standard library's `threading` or `multiprocessing` modules.

**Comment by robhagemans** [comment]
Hi @robhagemans , @nestormh

Ok, as I can understand, the first case you mention (using extensions), can be used for example to order from BASIC to do complex math calculations in python, and then send the results back to BASIC.

In this case, I have done a very simple test, with your current serial-topic branch: 

myextension.py:

```
def duplicate(n):
    try:
        return 2*int(n)
    except IndexError:
        return -1
```

for the basic code, I did a instrument routine file called py.rtn

10000 REM ************ PY.rtn ************ 
11020 B$="RESULT OF DUPLICATE(2)="+STR$(_DUPLICATE(2)):PRINT#4,B$
11030 RETURN
65529 REM proper last line

(The line numbers are from 10000 to 65529 the same as any other routine files like hp.rtn, which is what the main.asc program expect to read)

now, launch the brewer software with --extension=myextension, and from the command line of the Brewer Software, I run the py routine:

![image](https://user-images.githubusercontent.com/25931032/35595267-fbad028e-060d-11e8-987b-e63c4c7fad34.png)

It executes it properly and then goes back to the main screen of the brewer software. And in the file 4 (which corresponds to the D02018.185 file), it is written:

 PROGRAM start :  JAN 20/18 at 23:44:50
RESULT OF DUPLICATE(2)= 4


So in principle it works well.. but when trying to run the same py routine again, I got this:

![image](https://user-images.githubusercontent.com/25931032/35599629-946a29a8-0621-11e8-81e2-457995ecb4ec.png)

The unique strange thing I can notice is that in the log file:

[00:58:45.0250] DEBUG: files.py, open, loading file:hp.rtn as file number1
[00:58:45.0305] DEBUG: files.py, open, loading file:hp.rtn as file number0
[00:59:03.0275] DEBUG: files.py, open, loading file:d:\B02018.185 as file number1
[01:00:39.0862] DEBUG: files.py, open, loading file:d:\B02018.185 as file number1
[01:00:40.0500] DEBUG: files.py, open, loading file:py.rtn as file number1
[01:00:40.0551] DEBUG: files.py, open, loading file:py.rtn as file number0
[01:00:43.0674] DEBUG: files.py, open, loading file:d:\B02018.185 as file number1
[01:00:43.0674] DEBUG: files.py, open, loading file:d:\B02018.185 as file number1

I don't know if it is related with the problem but, why the routine files (*.rtn) are being opened twice, as file number 1 and then 0? (The hp routine is also loaded twice, but it does not have this repatability problem)

the line 2865 of the main.asc BASIC program, is that:

2840 GOSUB 1500:IF C$="menu" THEN 2615
2860 ON ERROR GOTO 2890
2865 RESTORE:READ PC$:IF C$=PC$ THEN 2880
2870 GOSUB 9500
2872 IF LEN(C$)=0 THEN 2600
2873 A$=C$:IF LEN(C$)>8 THEN C$=LEFT$(C$,8)
2875 GOSUB 6000:B$=A$:ON ERROR GOTO 2890:CLOSE 1:OPEN C$+E$ FOR INPUT AS 1:CLOSE 1
2876 CHAIN MERGE C$+E$, 2880, ALL, DELETE 10000-65529





Respect the second method you exposed (Inherit the session class); I have tested it, by adding the session inherit to the extension module: 

myextension.py:

```
import logging
from pcbasic.basic import Session

class ExtendedSession(Session):
    def __init__(self):
        Session.__init__(self, stdio=True, extension=self)

    def getHF2(self):
        hf=self.get_variable("HF%")
        print "HF%=",str(hf)
        return hf

def duplicate(n):
    try:
        return 2*int(n)
    except IndexError:
        return -1

def getHF(n):
    try:
        with ExtendedSession() as s:
            HF=s.getHF2()
        return HF
    except IndexError:
        return -1
```


for the basic code, I did a instrument routine file called px.rtn:

10000 REM ************ PX.rtn ************ 
11020 B$="HF% VALUE="+STR$(_GETHF(1)):PRINT#4,B$
11030 RETURN
65529 REM proper last line

(I cannot call to the _GETHF function with none arguments because I got a Syntax error, so I call it with a non used (1))
![image](https://user-images.githubusercontent.com/25931032/35600433-c5a9e43c-0625-11e8-9aab-e713d0b9b40a.png)

now, launch the brewer software with --extension=myextension, and from the command line of the Brewer Software, we run the px routine:

It executes it properly, the _GETHF(1) statment in BASIC calls to the getHF(n) function in the extension module, and it uses the ExtendedSession to get or set whatever in the BASIC space variables. finally it goes back to the main screen of the brewer software. In the file 4 (which corresponds to the D02018.185 file), it is written:

 PROGRAM start :  JAN 21/18 at 00:49:49
HF% VALUE= 0

But also if I run again the px routine, I got exactly the same error commented previously, Out of DATA in line 2865.
What can be the cause of that Out of DATA?

All in all I think this second method is more comfortable to get or set a more than one BASIC variables at once, than the previous method, since we have access to all the BASIC memory variables by using only one call.

**Comment by robhagemans** [comment]
Hi @Danitegue, @nestormh, I've moved this thread here from https://github.com/robhagemans/pcbasic/commit/77235db0363cc4b7f22aee50cd911b9c9b468a4d#comments . 
Please continue the conversation here.

**Comment by robhagemans** [comment]
Some remarks:

- Functions without arguments have no brackets in BASIC, unlike in Python. Hence the `Syntax error`. You can call a function simply as e.g. `A=_GETHF`. Compare for example `RND`, `CSRLIN`.
- I noticed that most classic `.RTN` routines have a single `DATA` statement with their name. So I think you need this to avoid the `Out of DATA`:
    `10500 DATA py`
- You're right that the Session class is more flexible than extensions. However, it's also likely to be more sensitive to future code changes - the API is not yet stable, constructor parameters will change, etc. So I think extensions will be less of a maintenance burden on your side. However, it's up to you, I think either can work. If you need to call BASIC subroutines from your Python script called by BASIC then the Session class is the only way, I think...
- Perhaps you could have a BASIC routine and Python extension that do the ugly work, and to create a new, simpler Python API for your users. The idea would be that they can write a Python function  or script without having to worry about BASIC. Their routine would then be in a module whose name should perhaps go in a variable input through the BASIC interface; you can then use `importlib` to load the module dynamically by name.You could perhaps provide all BASIC global variables to a dictionary, ideally with more descriptive names than `HF%` etc, and then ensure that changed values get stored in the BASIC variables again upon exit. Something like the below (I haven't tried, it may need some tweaking to work):

```
import importlib
variables = {}

def setvar(key, value):
    variables[key] = value

def getvar(key):
    return variables[key]

def callscript(name):
    user_module = importlib.importmodule(name)
    user_module.brewer_routine(variables)
```

Which is called from a BASIC routine (like your `PY.RTN`) doing something like this:

```
_SETVAR "some_description_of_hf", HF%
_SETVAR "next_global_you_might_need", G%
REM etcetera for all globals
_CALLSCRIPT SCRIPTNAME$
HF% = _GETVAR("some_description_of_hf")
G% = _GETVAR("next_global_you_might_need")
```
... and which in turn calls the user's script that has only a function

def brewer_routine(variables):
    do_something_useful(variables['some_description_of_hf'])
    # etcetera

you could probably do some more magic to make it even simpler for the user. However if people are used to the BASIC variable names anyway this might all be overkill.

**Comment by robhagemans** [comment]
As for the double opening, I think this snip of `main.asc` explains it:
```
2875 GOSUB 6000:B$=A$:ON ERROR GOTO 2890:CLOSE 1:OPEN C$+E$ FOR INPUT AS 1:CLOSE 1
2876 CHAIN MERGE C$+E$, 2880, ALL, DELETE 10000-65529
```
Looks like it opens the routine as a text file before loading it, presumably to check if it exists.

**Comment by Danitegue** [comment]
Hi Rob, 

As you commented, the repeatability problem was solved by adding the "DATA+ routine name" line in the BASIC code of the px or py routines. I hadn't noticed that, you are an eagle!, thanks a lot!

py.rtn:
10000 REM ************ PY.rtn ************ 
10010 DATA py
11020 B$="RESULT OF DUPLICATE(2)="+STR$(_DUPLICATE(2)):PRINT#4,B$
11030 RETURN
55555 '
65529 REM proper last line

Also many thanks for the BASIC functions info, now I know how to call a function without arguments from BASIC (I'm learning more BASIC every day... xd):

px.rtn:
10000 REM ************ PX.rtn ************ 
10010 DATA px
11020 B$="HF% VALUE="+STR$(_GETHF):PRINT#4,B$
11030 RETURN
55555 '
65529 REM proper last line

With respect the session class: Yes is very versatile, and I think is the way to go, but using or not using it  depends of the brewer community needs. Of course if at the end by the necessities we need to use it, some time would be needed to help you to maintain this functionality operative, and also adapt the extensions for the updates. For now I'm going to write some examples like the previous ones in the pcbasic_brewer branch readme, to explain what is possible and how to do it, and then, based in the requests of the brewer operators we will see in what way we can proceed. 

I suppose that the first steps could be basic things like:
- Trigger external python scripts once the daily schedule of measurements has been finished. (for make data backups, or upload data to the servers of eubrewnet)
- Make the extension modules plot the data of some vars, while a measurement is being done.

The next: 
- As you commented, we need to create and documentate an specializated pcbasic_brewer python API, easy to use, in which the community can have some of the old routines transcripted to python as examples, and where they can develop new ones using only python, without taking care of BASIC code anymore. 

The importlib method you mention can be useful also to have separate and shareable python routines, as individual modules. (Is very common to share customized routines for measurement campaigns, for example)

Respect the double oppening: Ok, now is clear. Thanks!

**Comment by Danitegue** [comment]
One last question, in order to know how far we can go with the inherited session class:

With it we can have acces to all the memory space of the BASIC program, but appart of reading and setting vars...

do you know if we can control the events of pcbasic from the python extensions?

I mean for example, once we are on the python extension called by a customized basic routine (py), order the brewer software to go back to the main menu (home key pressed event) write something in the command line and execute it (mouse click, and key pressed events)... emulating these events by code, from the extension.


Or... send something by the already opened com port using the ports.py read and write functions?

Would be something like a python remote control for the current basic software runing...

**Comment by robhagemans** [comment]
Heh - GW-BASIC is a lifetime learning experience. I've spent quite some time studying it and I'm not convinced I won't be surprised by some unexpected behaviour today or tomorrow. Sane people stay well away from it :) 

**"do you know if we can control the events of pcbasic from the python extensions?"**

_Official answer_: that's not supported in the API, I'm not sure if it will be.

_Unofficial answer_: once you've got hold of the `Session` object, you can do anything. 

What you describe is possible, you can simply put any event you like into the input queue - search the code for `queue` for some idea of what's going on here. The event-queues are thread-safe, which is why they're there in the first place, so it's totally possible to have a separate Python thread that emits, for example, keystoke events into the queue, which will then be consumed by PC-BASIC as if they were user keystrokes. There is also the `--keys` command-line option, but you can't control timing and you can't insert things like the Shift key that don't have an "e-ASCII" code. 

Note that threads in Python are a bit problematic as they don't really run in parallel due to the "global interpreter lock", which means your thread could lock up the PC_BASIC thread if you're not careful. It can be frustrating to debug, but it would certainly be possible.

Another approach generalising this would be to have a custom interface module. As you're aware, you can run PC-BASIC with various interfaces (text, pygame, sdl2) which are implemented as modules interfacing those queues. If you have your own interface it would completely control the keys that go into PC-BASIC and it can decide what to do with the screen output. You could build a complete GUI for the Brewer, let's say with `tkinter`, `wxpython` or `pyqt` if you feel like it and have the time...

The big caveat is, of course, that it would break if I re-implement some of the internals - e.g. some of the events might change how they work in future versions. I'm not ready to tie myself down completely to the current implementation and keep supporting it, beyond the basic structure of the Session API that I've put in the docs. 

However if you do want to go this way, I'd prefer it to be able to be an application of PC-BASIC rather than a fork - if everybody uses the same codebase of PC-BASIC it would be much easier to find and solve bugs than if each use their own special-purpose fork; and the "developer base" for PC-BASIC is small enough as it is. So in that case we need to work out if we can abstract some "interface contract" that is likely to stay stable, and use that. (Realistically you'll probably still work with a specific version/tag/branch/commit of PC-BASIC but at least it would make it feasible to keep it up to date once in a while)

**Comment by robhagemans** [comment]
Of course, long term, it might make sense to replace the core of the BASIC software (like `main.asc`) with Python, and run only the "legacy" `.RTN`s through PC-BASIC, which would be simpler. But that would take a lot more effort to make work in the first place, so it's probably better to take it gradually.

**Comment by Danitegue** [comment]
Ok that's very interesting, and can be useful for us in the future.

Yes, I agree that the best option would be applications of PCBASIC rather than a highly modified fork (Actually the pcbasic-brewer fork is almost a clone of pcbasic, with only a few more logging lines in files.py, ports.py, and memory.py that I need until we ensure that the communication with the instrument works properly in all the cases). I will try to mantain it as close as possible to your main version, and not to perform big modifications, since I think it is more productive for both us.

The first big goal was to be able to communicate the old basic brewer software with the external world, and with the actual version of pcbasic using extensions it is done.

For the next steps, we will evaluate the options, having into account all your given recommendations. 

Thanks a lot for your wisdom!. I will keep you informed

**Comment by Danitegue** [comment]
Hi @robhagemans , @nestormh

Yesterday we were writting some examples of how to use the extensions, and we noticed that the inherited session method doesn't work as expected, or perhaps we are using it wrongly.

The problem is that when it is created the inherited session class, we could see doing debugging that it is empty, I mean, this inherited session class does not contain the variables stored in the main session class. Is like if it would be initializated a new one, empty. Also we could see that all changes done in this inherited class are not transmitted to the main session class.

This  obviously affects to the .get and .set methods.

Respect the .get method, you can ask the value of any variable you can imagine (existing or not in basic) with the s.get() method, and the answer is always the same, a zero (0). 

When we change the value of an existing BASIC variable with the s.set() method, it cannot find any already existing variable in the inherited session class and it creates a new one. But when returning to BASIC, all the changes done in the inherited session class, are not present in the main session class.  

Example:

myextension.py:
```
from pcbasic.basic import Session


class ExtendedSession(Session):
    def __init__(self):
        Session.__init__(self, stdio=True, extension=self)

    def getHF_session(self):
        hf = self.get_variable("HF%")
        return hf

    def setHF_session(self, value):
        self.set_variable("HF%", value)


def HFswitch():
    with ExtendedSession() as s:
        HF = s.getHF_session()
        if HF == 1:
            s.setHF_session(0)
        elif HF == 0:
            s.setHF_session(1)
    return ""
```


basic routine "pv.rtn"

```
10000 REM ************ PX.rtn ************
10010 DATA px
10015 HF%=0
11020 B$="HF% VALUE="+STR$(HF%):PRINT#4,B$
11030 TEMP$=_HFSWITCH
11040 B$="HF% VALUE="+STR$(HF%):PRINT#4,B$
11050 RETURN
55555 '
65529 REM proper last line
```

the result in the output file (C:\PCBasic_Brewer_Repo\brw#185\bdata185\D03718.185) should be 
HF% VALUE=0
HF% VALUE=1

but the fact is that we obtain
HF% VALUE=0
HF% VALUE=0

We will use the basic extensions for now (without the inherited class), until looking a solution for that.
Regards

**Comment by robhagemans** [comment]
Hi, yes, sorry, that way it will not work. If you launch PC-BASIC in the normal way it will create a normal `Session`; all that's happening here is that on every call of `HFswitch()` you're initialising another fresh copy of PC-BASIC with an `ExtendedSession` and no screen interface, and change `HF%` in that copy.

You'll need to run PC-BASIC with the `ExtendedSession` in the first place, and run the Brewer program from there. Something like

```
with ExtendedSession(stdio=True) as s:
     s.execute('RUN "main.asc"')
```

although that will give you only text flowing on the command line, as no interface is being used.

To also set up an interface and use it with the `ExtendedSession`, you'd need to reproduce some of the launch code in `pcbasic/main.py` that sets up an interface and links it to the session object. You could do this from a separate script that imports the `pcbasic` package. Hypothetically, you could use the same script to set the session parameters and the environment variables you need, so you won't need to mess around with the INI file and batch scripts anymore...

**Comment by Danitegue** [comment]
ok I undestand now. We will see if it is worth doing in that way so. Thanks!

El 7/2/2018 21:02, "Rob Hagemans" <notifications@github.com> escribió:

Hi, yes, sorry, that way it will not work. If you launch PC-BASIC in the
normal way it will create a normal Session; all that's happening here is
that on every call of HFswitch() you're initialising another fresh copy of
PC-BASIC with an ExtendedSession and no screen interface, and change HF% in
that copy.

You'll need to run PC-BASIC with the ExtendedSession in the first place,
and run the Brewer program from there. Something like

with ExtendedSession(stdio=True) as s:
     s.execute('RUN "main.asc"')

although that will give you only text flowing on the command line, as no
interface is being used.

To also set up an interface and use it with the ExtendedSession, you'd need
to reproduce some of the launch code in pcbasic/main.py that sets up an
interface and links it to the session object. You could do this from a
separate script that imports the pcbasic package. Hypothetically, you could
use the same script to set the session parameters and the environment
variables you need, so you won't need to mess around with the INI file and
batch scripts anymore...

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/robhagemans/pcbasic/issues/60#issuecomment-363909334>,
or mute the thread

**Comment by robhagemans** [comment]
Essentially, this:

```
"""
PC-BASIC/Brewer launcher
"""

import logging
import threading

from pcbasic import ansipipe
from pcbasic import basic
from pcbasic import config
from pcbasic import interface

class ExtendedSession(basic.Session):
    """Your class here."""
    pass

def run(*arguments):
    """Set up interface and launch session."""
    with config.TemporaryDirectory(prefix='pcbasic-') as temp_dir:
        # get settings and prepare logging
        settings = config.Settings(temp_dir, arguments)
        # start an interpreter session with interface
        try:
            # initialise queues
            iface = interface.Interface(
                        *settings.get_interfaces(),
                        video_params=settings.get_video_parameters(),
                        audio_params=settings.get_audio_parameters())
        except interface.InitFailed:
            logging.error('Failed to initialise interface.')
            return
        thread = threading.Thread(
                    target=run_session,
                    args=(iface,),
                    kwargs=settings.get_session_parameters())
        try:
            # launch the BASIC thread
            thread.start()
            # run the interface
            iface.run()
        finally:
            iface.quit_input()
            thread.join()

def run_session(iface=None, **session_params):
    """Run an interactive BASIC session."""
    try:
        with ExtendedSession(iface, **session_params) as session:
            session.execute('RUN "main.asc"')
    finally:
        if iface:
            iface.quit_output()


if __name__ == "__main__":
    run()
```

Not quite as elegant, but it does seem to work.

**Comment by Danitegue** [comment]
ok I undestand. We will give a look to this option.  Thanks for your support, regards.
