### ISSUE TITLE
False positive on Antiy, Jiangmin and Baidu

### ISSUE THREAD

**Issue by shnopy** [robhagemans/pcbasic#70]
3 AV detected this as a Trojan.

https://www.virustotal.com/#/file/b7236468a8aa83b2a2c92e673639229f5a261e5aa409dddee5a9c6d61103ab38/detection

**Comment by robhagemans** [comment]
Odd. I built that executable using NSIS, it's just a packaged up version of the Python code for PC-BASIC together with the Python interpreter. The hash is correct so it's not been messed with after that.
No idea why it gets flagged, it may be that these checkers flag any NSIS package?

**Comment by robhagemans** [comment]
Apparently it's not uncommon with NSIS packages: http://nsis.sourceforge.net/NSIS_False_Positives
