### ISSUE TITLE
[QUESTION] Would this be doable / possible? If so, do you have any pointers you could give?

### ISSUE THREAD

**Issue by smeggingsmegger** [robhagemans/pcbasic#73]
I have a GW-BASIC application: (~9000) lines with lots of GOSUB / GOTO calls. I am looking to translate this to Python and it occurs to me that this project already figured this out, more or less.

Would it be possible to use some of the libraries in this project to help produce something like that?

Thanks in advance!

**Comment by robhagemans** [comment]
Hi, PC-BASIC won't really help you translate the code but it could certainly help you interface with the BASIC code - for example, you can call the code from Python, query its variables, etc. You can also call Python code from BASIC.

So it all depends a bit on what you want to do with the code - if you just need to run it, PC-BASIC can do that; if you need to extend it but you don't want to do that in BASIC then you could use it to write new functionality in Python and make it work together. Or you could take parts of the program (perhaps the more incomprehensible bits of spaghetti BASIC) and run those from a Python framework.

For some pointers on how to interface Python and BASIC (if that indeed works for your purposes) you could have a look here: http://robhagemans.github.io/pcbasic/doc/2.0/#dev

This part of the documentation is still a bit sparse and the API is still under development, but there is an example that executes some BASIC code from Python and then in turn calls Python code from BASIC  (in the example, the built-in `random` module, but it could be your own module or class).

Let me know how you get on, happy to help with specifics

**Comment by smeggingsmegger** [comment]
Thanks for the information. That was really helpful! I will definitely be using this as I work on the overall translation from BASIC to Python. I've been executing the program using PC-BASIC already. This is an amazing project. You should be really proud.
