### ISSUE TITLE
`renum` Illegal function call (2.0.0)

### ISSUE THREAD

**Issue by jacobcarpenter** [robhagemans/pcbasic#80]
`renum` results in `Illegal function call` in 2.0.0 on Mac OS.

In a new PC-Basic 2.0.0 instance, enter
```
10 ?"rob rocks
20 goto 10
renum
```

I would expect `renum` to successfully execute (as a no-op in this case), but instead, PC-Basic prints `Illegal function call`.

`renum` does work as expected in v 1.2.13 on Mac.

**Comment by robhagemans** [comment]
Thanks! Finally an easy bug :)

**Comment by robhagemans** [comment]
Fixed by commit  44a61e5

**Comment by robhagemans** [comment]
This'll be in 2.0.1
