### ISSUE TITLE
PC-BASIC just quits (no errors/warnings) with COM port option

### ISSUE THREAD

**Issue by josh2112** [robhagemans/pcbasic#84]
Running PC-BASIC 1.2.13 on a Lubuntu Linux VM.  The VM is configured with a serial port which VirtualBox redirects to TCP localhost:7000 on the host machine.  I'm pretty confident in the serial port configuration -- when I echo characters to the port in the guest, my simple python TCP server on the host receives the characters.

However, when I pass PC-BASIC the option to enable COM1 as /dev/ttyS0, it just closes. No output, no warnings or errors.  If I enable the log file, it is empty.  I am using the PCjr preset but I get the same result without that preset. What gives?

```
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --preset=pcjr
WARNING: Failed to initialise sound. Sound will be disabled.
PC-BASIC 1.2.13
(C) Copyright 2013--2018 Rob Hagemans.
59694 Bytes free
Ok 
system
josh2112@jf334-lubuntu-vm:~$ ls -la /dev/ttyS0
crw-rw-rw- 1 root dialout 4, 64 Oct 15 12:01 /dev/ttyS0
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --preset=pcjr --com1=PORT:0
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --preset=pcjr --com1=PORT:/dev/ttyS0
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --com1=PORT:/dev/ttyS0
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --com1=PORT:/dev/ttyS0 --logfile=pcbasic.log
josh2112@jf334-lubuntu-vm:~$ cat pcbasic.log 
josh2112@jf334-lubuntu-vm:~$ 
```

**Comment by robhagemans** [comment]
Hi, thanks for the report. Looks like there is a crash very early on in the startup sequence. 

Could you give it a try with version 2.0.0 ? It's had a lot more testing of the serial port so we might be able to get some more information out of it

**Comment by josh2112** [comment]
Hi Rob, thanks for responding so quickly!  Just tried PC-BASIC 2 on the same VM and it works perfectly:

```
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --com1=port:/dev/ttyS0
PC-BASIC 2.0.0                                                                  
(C) Copyright 2013--2018 Rob Hagemans.                                          
60300 Bytes free                                                                
Ok                                                                              
open "com1:" as #1                                                              
Ok                                                                              
print #1, "hello world"                                                         
Ok                                                                              
system                                                                          
```
```
> python tcpserver.py
Listening on localhost:7000...
New connection from ('127.0.0.1', 64079)
b'h'b'e'b'l'b'l'b'o'b' 'b'w'b'o'b'r'b'l'b'd'b'\r
````

But while testing this I ran into another issue... the PCjr preset doesn't seem to be working on PC-BASIC 2.0.  I'll file another issue for that.

Thanks!
