### ISSUE TITLE
PC-BASIC 2.0.0 quits (no errors/warnings) with --preset=pcjr or --text-width=40

### ISSUE THREAD

**Issue by josh2112** [robhagemans/pcbasic#85]
Running PC-BASIC 2.0.0 on a Lubuntu Linux VM.  The PCjr preset (as documented in [emulation targets](https://robhagemans.github.io/pcbasic/doc/#presets), and which works fine on 1.2.13), causes PC-BASIC to immediately close with no output.

```
josh2112@jf334-lubuntu-vm:~$ pcbasic -b
PC-BASIC 2.0.0                                                                  
(C) Copyright 2013--2018 Rob Hagemans.                                          
60300 Bytes free                                                                
Ok                                                                              
system                                                                          
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --preset=pcjr
josh2112@jf334-lubuntu-vm:~$ pcbasic -b --preset=pcjr --logfile=pcbasic.log
josh2112@jf334-lubuntu-vm:~$ cat pcbasic.log 
josh2112@jf334-lubuntu-vm:~$ 
```

Assuming the preset had been removed, I tried to figure out the equivalent combination of options.  I believe it's `--syntax=pcjr --video=pcjr --text-width=40`, but I've found that adding the `text-width` option produces another "silent close" where PC-BASIC crashes back to the console with no errors or warnings.

**Comment by josh2112** [comment]
I see in [pcbasic/config.py](https://github.com/robhagemans/pcbasic/blob/902808318e744432c643c6d2be2eaa91136a6645/pcbasic/config.py) that the "pcjr" preset expands into:

```
syntax=pcjr
term=[PROGRAM_PATH]/PCTERM.BAS
video=pcjr
font=vga
codepage=437
reserved-memory=4035
text-width=40
video-memory=16384
```

**Comment by robhagemans** [comment]
Thanks for reporting - this is a known issue and has been fixed in the current `master` branch, will be in 2.0.1

**Comment by josh2112** [comment]
Ok, thanks Rob.  I guess in the meantime the workaround is to create my own preset with the options listed above, minus `text-width`...

**Comment by robhagemans** [comment]
Yes, that's probably the best for now, until the release. The only difference will be stat it starts in 80-column mode instead of 40-column mode, but you can then use `WIDTH 40` if needed

**Comment by robhagemans** [comment]
The documentation for 2.0 is at http://robhagemans.github.io/pcbasic/doc/2.0/ by the way, there are a few differences with 1.2 (though not really where it comes to PCjr)
