### ISSUE TITLE
Crash on formatting with thousands separators in PRINT USING (v1.2)

### ISSUE THREAD

**Issue by RBARROS2** [robhagemans/pcbasic#89]
![pc-basic-1 2 bug](https://user-images.githubusercontent.com/45069323/48565798-61198b00-e8c7-11e8-9186-1cdbc3f720c8.jpg)
[PC-BASIC-1.2 BUG.docx.pdf](https://github.com/robhagemans/pcbasic/files/2586107/PC-BASIC-1.2.BUG.docx.pdf)

**Comment by robhagemans** [comment]
Thanks for reporting this and for including the reproducing code. I can reproduce this with 1.2.13 and will investigate a fix.

This bug does not appear to affect v2.0

**Comment by RBARROS2** [comment]
Rob,

The bug was not in PC-BASIC  when I used it a year ago if that helps.

Rich
On 11/15/2018 11:50:09 AM, Rob Hagemans <notifications@github.com> wrote:
Thanks for reporting this and for including the reproducing code. I can reproduce this with 1.2.13 and will investigate a fix.
This bug does not appear to affect v2.0

**Comment by robhagemans** [comment]
Fixed by commit a26181b, will be included in 1.2.14
