### ISSUE TITLE
Full Screen in Windows 64 and 32 bit backs out of fullscreen by default

### ISSUE THREAD

**Issue by hseiken** [robhagemans/pcbasic#91]
In both win8 and win7 (64 and 32 bits respectively), F11+F attempts full screen the reverts back to windowed with default config file.

**Comment by robhagemans** [comment]
Hi @hseiken, what version are you using? F11+F works normally for me on Win7 with 2.0.1 . With 1.2.14 it seems to need F11+F twice, but the second time works consistently.

**Comment by hseiken** [comment]
Okay, for some reason, when I try it now on the 32bit system, it works. I changed the config to have it start fullscreen, which was the only change I made to it with regards to display. It doesn't start in fullscreen, but now it allows switching to full screen. 

So  I guess it's not an issue. Thanks for the quick response.
