### ISSUE TITLE
PLAY causes crash

### ISSUE THREAD

**Issue by jefbed** [robhagemans/pcbasic#94]
## Bug report

**Problem**
Entering the statement "PLAY" causes an immediate exception.  PLAY with a parameter crashes pc-basic as well--no parameters defined is simply the simplest case causing the problem repeatably.

**Steps**

1.  Type "PLAY"

**Program**
10 PLAY "abc"

**Crash log**
PC-BASIC crash log
====================================================================================================
FATAL ERROR
version   2.0.2 []  2019-03-07 01:40:24.461102
python    3.7.2 [64bit ELF] 
platform  Linux-5.0.0-arch1-1-ARCH-x86_64-with-arch
interface VideoSDL2, AudioSDL2
statement :PLAY

interpreter.py:120, loop
interpreter.py:109, parse
statements.py:82, parse_statement
sound.py:266, play_
RuntimeError: generator raised StopIteration

This is a bug in PC-BASIC.
Sorry about that. To help improve PC-BASIC, please file a bug report at
  https://github.com/robhagemans/pcbasic/issues
Please include the messages above and as much information as you can about what you were doing and how this happened. Please attach the log file
  /home/jefbed/.local/share/pcbasic-2.0/crash-20190307-3op93v_p.log
Thank you!

Press a key to close this window.
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/sound.py", line 266, in <genexpr>
    mml_list = list(values.next_string(args) for _ in range(3))
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/values/values.py", line 79, in next_string
    expr = next(args)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/guard.py", line 66, in protect
    yield
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/main.py", line 114, in run_session
    session.interact()
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/api.py", line 124, in interact
    self._impl.interact()
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/implementation.py", line 322, in interact
    self.interpreter.loop()
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/interpreter.py", line 120, in loop
    self.parse()
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/interpreter.py", line 109, in parse
    self.parser.parse_statement(ins)
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/parser/statements.py", line 82, in parse_statement
    self._callbacks[c](parse_args(ins))
  File "/usr/lib/python3.7/site-packages/pcbasic-2.0.2-py3.7.egg/pcbasic/basic/sound.py", line 266, in play_
    mml_list = list(values.next_string(args) for _ in range(3))
RuntimeError: generator raised StopIteration

==== Screen Pages ==================================================================================
   +--------------------------------------------------------------------------------+
 0 |PC-BASIC 2.0.2                                                                  | 14
 1 |(C) Copyright 2013--2019 Rob Hagemans.                                          | 38
 2 |60300 Bytes free                                                                | 16
 3 |Ok?                                                                             |  3
 4 |play                                                                            |  4
 5 |                                                                                |  0
 6 |                                                                                |  0
 7 |                                                                                |  0
 8 |                                                                                |  0
 9 |                                                                                |  0
10 |                                                                                |  0
11 |                                                                                |  0
12 |                                                                                |  0
13 |                                                                                |  0
14 |                                                                                |  0
15 |                                                                                |  0
16 |                                                                                |  0
17 |                                                                                |  0
18 |                                                                                |  0
19 |                                                                                |  0
20 |                                                                                |  0
21 |                                                                                |  0
22 |                                                                                |  0
23 |                                                                                |  0
24 | 1LIST   2RUN   3LOAD"  4SAVE"  5CONT  6,"LPT1 7TRON  8TROFF 9KEY    0SCREEN| 80
   +--------------------------------------------------------------------------------+
   +--------------------------------------------------------------------------------+
 0 |                                                                                |  0
 1 |                                                                                |  0
 2 |                                                                                |  0
 3 |                                                                                |  0
 4 |                                                                                |  0
 5 |                                                                                |  0
 6 |                                                                                |  0
 7 |                                                                                |  0
 8 |                                                                                |  0
 9 |                                                                                |  0
10 |                                                                                |  0
11 |                                                                                |  0
12 |                                                                                |  0
13 |                                                                                |  0
14 |                                                                                |  0
15 |                                                                                |  0
16 |                                                                                |  0
17 |                                                                                |  0
18 |                                                                                |  0
19 |                                                                                |  0
20 |                                                                                |  0
21 |                                                                                |  0
22 |                                                                                |  0
23 |                                                                                |  0
24 |                                                                                |  0
   +--------------------------------------------------------------------------------+
   +--------------------------------------------------------------------------------+
 0 |                                                                                |  0
 1 |                                                                                |  0
 2 |                                                                                |  0
 3 |                                                                                |  0
 4 |                                                                                |  0
 5 |                                                                                |  0
 6 |                                                                                |  0
 7 |                                                                                |  0
 8 |                                                                                |  0
 9 |                                                                                |  0
10 |                                                                                |  0
11 |                                                                                |  0
12 |                                                                                |  0
13 |                                                                                |  0
14 |                                                                                |  0
15 |                                                                                |  0
16 |                                                                                |  0
17 |                                                                                |  0
18 |                                                                                |  0
19 |                                                                                |  0
20 |                                                                                |  0
21 |                                                                                |  0
22 |                                                                                |  0
23 |                                                                                |  0
24 |                                                                                |  0
   +--------------------------------------------------------------------------------+
   +--------------------------------------------------------------------------------+
 0 |                                                                                |  0
 1 |                                                                                |  0
 2 |                                                                                |  0
 3 |                                                                                |  0
 4 |                                                                                |  0
 5 |                                                                                |  0
 6 |                                                                                |  0
 7 |                                                                                |  0
 8 |                                                                                |  0
 9 |                                                                                |  0
10 |                                                                                |  0
11 |                                                                                |  0
12 |                                                                                |  0
13 |                                                                                |  0
14 |                                                                                |  0
15 |                                                                                |  0
16 |                                                                                |  0
17 |                                                                                |  0
18 |                                                                                |  0
19 |                                                                                |  0
20 |                                                                                |  0
21 |                                                                                |  0
22 |                                                                                |  0
23 |                                                                                |  0
24 |                                                                                |  0
   +--------------------------------------------------------------------------------+
==== Scalars =======================================================================================

==== Arrays ========================================================================================

==== Strings =======================================================================================

==== Program Buffer ================================================================================
b'00' b'0000' (ENDS) b'' b''
==== Program =======================================================================================
==== Options =======================================================================================
[]

**Notes**

PC-BASIC version:  2.0.2
Operating system version:  Arch Linux distribution, up to date, GNU/Linux 5.0.0 kernel

**Comment by robhagemans** [comment]
Hi, thanks for reporting!

This issue is due to the implementation of https://www.python.org/dev/peps/pep-0479/ in Python 3.7, and has been fixed by commit c898cdbcb, which will be included in 2.0.3. Until that is released, you could use Python 3.5 or 3.6 as a workaround.

Thanks,
Rob
