### ISSUE TITLE
INT should round towards negative infinity instead of towards zero

### ISSUE THREAD

**Issue by dnprod** [robhagemans/pcbasic#96]
## Bug report

i thought the int() function should behave like the C runtime floor() function, but it seems to misbehave
on values greater than -1.0 and smaller than 0.0
int(-0.6) returns zero, i expected -1

am i misunderstanding some subtely of the int() function, or is it really a bug?

**Program**
10 POS1=1.6
20 POS0=.6
30 POSM0=-.6
40 POSM1=-1.6
50 PRINT "       val: ",POS1,POS0,POSM0,POSM1
60 PRINT "int expect: ",1,0,-1,-2
70 IPOS1=INT(POS1)
80 IPOS0=INT(POS0)
90 IPOSM0=INT(POSM0)
100 IPOSM1=INT(POSM1)
110 PRINT "       got: ",IPOS1,IPOS0,IPOSM0,IPOSM1
120 IIPOS1=INT(1.6)
130 IIPOS0=INT(.6)
140 IIPOSM0=INT(-.6)
150 IIPOSM1=INT(-1.6)
160 PRINT" still got: ",IIPOS1,IIPOS0,IIPOSM0,IIPOSM1

Ok                                                                              
run                                                                             
       val:    1.6           .6           -.6           -1.6                    
int expect:    1             0            -1            -2                      
       got:    1             0             0            -2                      
 still got:    1             0             0            -2                      
Ok 

PC-BASIC version:  1.2
Operating system version:  win7/64

thank-you for a cool retro toy :)

**Comment by dnprod** [comment]
in case hardware instructions are involved in the math, my machine is
AMD Phenom II X4 830 @ 2.80 GHz with 16.0 GB (15.7 GB usable) memory

**Comment by robhagemans** [comment]
Thanks for reporting! This looks like a bug as `INT(-0.5)` should give `-1` as per documentation and GW-BASIC behaviour. I'm a bit surprised I missed this before...

Rob

**Comment by udhos** [comment]
I think that INT(-0.1) should give -1 as well.

See: 

```
PRINT INT(98.89)
 98
PRINT INT(-12.11)
 -13

```
From: https://hwiegman.home.xs4all.nl/gw-man/INT.html

It is interesting to compare with FIX():

http://www.antonis.de/qbebooks/gwbasman/fix.html

- GW-BASIC INT() is similar to C floor().
- GW-BASIC FIX() is similar to C trunc().

**Comment by dnprod** [comment]
the code i was looking at (calculates moon rise/set time) seem to employ the sequence
   value = num - int(num)
several times to map numbers into a positive value between 0 and 1 before tossing them into trig functions.
the bug allowed a negative value to slip into the later calculations.
if this trick was commonly used, i could imagine this bug creating other weird bugs in trig-using
tools (audio ?) since the downstream math would not be expecting negative values.
in my case the moon was up in the daytime every day -- only fatal to goths :)

**Comment by robhagemans** [comment]
fixed by commits 14840029 (1.2 branch) and 843da932c (2.0 branch)
